### PR TITLE
Update bower.json

### PR DESCRIPTION
**Pull request by kappuccino**
Reflect the latest version.
Allow to get the version 1.3.20 you get from npm i storejs

### CODE REVIEW

**Comment by marcuswestin** [comment]
Thanks!

**Comment by kappuccino** [comment]
`bower cache clean`
`bower install storejs`

> bower store.js#^1.3.20    ENORESTARGET No tag found that was able to satisfy ^1.3.20
> Additional error details:
> Available versions in git://github.com/jaywcjlove/store.js.git: 1.0.8, 1.0.6, 1.0.5, 1.0.4, 1.0.3, 1.0.2, 1.0.1

`bower install storejs` do not works and still install the 1.0.7

w

**Comment by marcuswestin** [comment]
Tag v1.3.20 exists. Please help figure out how to make bower refer to it
instead of 1.3.20

**Comment by kappuccino** [comment]
My bad... bower install storejs is related to https://github.com/jaywcjlove/store.js and not your repo.
bower install store-js makes the job...

i should have read it correctly

by the way, the version field in bower.config file is a still a good idea :)

**Comment by marcuswestin** [comment]
Good to hear! Cheers :)

**Pull request merged**
