### PR TITLE
feature noop when not in DOM environment

### LINKED ISSUE #129: feature: noop if no supported options found.
Tried to use this package in a universal(read: isomorphic) app. It threw `cannot read property 'documentElement' of undefined`.

What I was hoping that this package would just noop in the server and work as expected in the browser. I would be down to form a PR for this. It just involves checking for property existence.

### PR DESCRIPTION
**Pull request by BerkeleyTrue**
closes #129

### CODE REVIEW

**Comment by BerkeleyTrue** [comment]
Any feedback on this?

**Comment by marcuswestin** [comment]
Hey, sorry for the very, very late response.

It turns out that node.js was supported just fine up until 7c65e0a6.

I intend to make store.js work in node again.

**Comment by BerkeleyTrue** [comment]
@marcuswestin No worries. I've been using this PR in production now for a while without issue.

**Comment by marcuswestin** [comment]
store.js now works in node.js again. See https://github.com/marcuswestin/store.js/blob/master/tests/node-test-runner.js for example usage with a node compatible localstorage module.

**Pull request merged**
